# Generated by Django 3.2.7 on 2021-09-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(unique=True, verbose_name='글번호')),
                ('writer', models.CharField(max_length=30, verbose_name='작성자')),
                ('subject', models.CharField(max_length=100, verbose_name='제목')),
                ('passwd', models.CharField(max_length=20, verbose_name='비밀번호')),
                ('content', models.CharField(max_length=2000, verbose_name='내용')),
                ('readcount', models.IntegerField(default=0, verbose_name='조회수')),
                ('ref', models.IntegerField(verbose_name='그룹화아이디')),
                ('restep', models.IntegerField(verbose_name='글순서')),
                ('relevel', models.IntegerField(verbose_name='글레벨')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('ip', models.CharField(max_length=20, verbose_name='IP')),
            ],
        ),
    ]
